server:
  port: 8085

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:hotel_user}
    password: ${DB_PASSWORD:hotel_pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api/notifications/v3/api-docs
  swagger-ui:
    path: /api/notifications/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
